version: '3.7'
services:
  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always
  mysql-container:
    image: mysql:8.0.15
    ports:
      - 2053:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root123 --execute \"SHOW DATABASES;\""
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=spring_app_db
    restart: always
  account-service:
    image: account-service:latest
    ports:
      - 8089:8089
    depends_on:
     - eureka-server
     - mysql-container
    environment:
      SPRING_APPLICATION_JSON: '{
      "flyway.enabled": "true",
      "l10n.flyway.clean" : "true",
      "spring.jpa.database" : "MYSQL",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.datasource.url" : "jdbc:mysql://mysql-container:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true",
      "spring.datasource.username" : "app_user",
      "spring.datasource.password" : "test123",
      "spring.application.name" : "account-service",
      "spring.datasource.driverClassName" : "com.mysql.jdbc.Driver",
      "server.port": "8089",
      "eureka.client.service-url.defaultZone": "http://eureka-server:8761/eureka/",
      "eureka.instance.preferIpAddress": "true",
      "eureka.client.registerWithEureka": "true",
      "eureka.client.fetchRegistry": "true"
      }'
    restart: always
  bank-service:
    image: bank-service:latest
    ports:
      - 8085:8085
    depends_on:
      - mysql-container
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{
      "flyway.enabled": "true",
      "l10n.flyway.clean" : "true",
      "spring.jpa.database" : "MYSQL",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.datasource.url" : "jdbc:mysql://mysql-container:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true",
      "spring.datasource.username" : "app_user",
      "spring.datasource.password" : "test123",
      "spring.application.name" : "bank-service",
      "spring.datasource.driverClassName" : "com.mysql.jdbc.Driver",
      "server.port": "8085",
      "eureka.client.service-url.defaultZone": "http://eureka-server:8761/eureka/",
      "eureka.instance.preferIpAddress": "true",
      "eureka.client.registerWithEureka": "true",
      "eureka.client.fetchRegistry": "true"
      }'
    restart: always
  branch-service:
    image: branch-service:latest
    ports:
      - 8086:8086
    depends_on:
      - mysql-container
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{
      "flyway.enabled": "true",
      "l10n.flyway.clean" : "true",
      "spring.jpa.database" : "MYSQL",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.datasource.url" : "jdbc:mysql://mysql-container:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true",
      "spring.datasource.username" : "app_user",
      "spring.datasource.password" : "test123",
      "spring.application.name" : "branch-service",
      "spring.datasource.driverClassName" : "com.mysql.jdbc.Driver",
      "server.port": "8086",
      "eureka.client.service-url.defaultZone": "http://eureka-server:8761/eureka/",
      "eureka.instance.preferIpAddress": "true",
      "eureka.client.registerWithEureka": "true",
      "eureka.client.fetchRegistry": "true"
      }'
    restart: always
  customer-service:
    image: customer-service:latest
    ports:
      - 8087:8087
    depends_on:
      - mysql-container
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{
      "flyway.enabled": "true",
      "l10n.flyway.clean" : "true",
      "spring.jpa.database" : "MYSQL",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.datasource.url" : "jdbc:mysql://mysql-container:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true",
      "spring.datasource.username" : "app_user",
      "spring.datasource.password" : "test123",
      "spring.application.name" : "customer-service",
      "spring.datasource.driverClassName" : "com.mysql.jdbc.Driver",
      "server.port": "8087",
      "eureka.client.service-url.defaultZone": "http://eureka-server:8761/eureka/",
      "eureka.instance.preferIpAddress": "true",
      "eureka.client.registerWithEureka": "true",
      "eureka.client.fetchRegistry": "true"
      }'
    restart: always
  zuul-service:
    image: zuul-service
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    restart: always
  transaction-service:
    image: transaction-service:latest
    ports:
      - 8088:8088
    depends_on:
      - mysql-container
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{
      "flyway.enabled": "true",
      "l10n.flyway.clean" : "true",
      "spring.jpa.database" : "MYSQL",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.datasource.url" : "jdbc:mysql://mysql-container:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true",
      "spring.datasource.username" : "app_user",
      "spring.datasource.password" : "test123",
      "spring.application.name" : "transaction-service",
      "spring.datasource.driverClassName" : "com.mysql.jdbc.Driver",
      "server.port": "8088",
      "eureka.client.service-url.defaultZone": "http://eureka-server:8761/eureka/",
      "eureka.instance.preferIpAddress": "true",
      "eureka.client.registerWithEureka": "true",
      "eureka.client.fetchRegistry": "true"
      }'
    restart: always
