server:
  port: ${server_port:9090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}

spring:
  application:
    name: zuul-server

management:
  security:
    enabled: false
